"""TikTok, Course 5: classify a video as a claim or an opinion, and ask who did the work.

The obvious version of this project fits a random forest, reports 99.6 % and calls it a
success. This one fits the forest, reports the same number, and then spends the rest of its
time proving that **the algorithm contributed almost nothing**.

Run it:
    python projects/curso5/tiktok/02_scripts/tiktok_trees.py

Reads Kevin's CSV read-only, writes figures to 03_figures/ and every publishable number to
04_reports/model_results.json.

The control that makes the point: a decision tree of **one single question about one single
column** is fitted alongside the tuned forest. If the forest with nine variables and three
hundred trees cannot beat one question, then the performance was in the data before any
model touched it.

Course 2 already found that signal from the other side: a claim gets 101 times the views of
an opinion, and the two distributions barely overlap. This project is what that finding
looks like once you try to build on it.

And it ends somewhere uncomfortable. The data is synthetic, generated by TikTok for the
certificate, and the single threshold lands at 10,031 views while the most-watched opinion
in the whole file has 9,998. That is not a behaviour anyone discovered. It is the seam of
how the file was manufactured, and a model that scores 99.6 % on it has measured the
generator, not the platform.
"""

from __future__ import annotations

import sys
import time
import warnings
from pathlib import Path

import numpy as np
import pandas as pd

warnings.filterwarnings("ignore")

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (accuracy_score, f1_score, precision_score, recall_score,
                             roc_auc_score)
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.tree import DecisionTreeClassifier
from xgboost import XGBClassifier

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))  # projects/, for common.py
from common import (  # noqa: E402
    ANNOTATION, AZURITE, CAPTION, GOLD, GRAPHITE, HAIRLINE, MUTED, PANEL_TITLE, SURFACE,
    TALL, TITLE, WIDE, Results, banner, dataset, decimal, figures_dir, save_figure, style,
    thousands,
)

import matplotlib.pyplot as plt  # noqa: E402

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")

SLUG = "tiktok"
COURSE = "curso5"
FIGURES = figures_dir(COURSE, SLUG)
SEED = 42

COUNTERS = ["video_view_count", "video_like_count", "video_share_count",
            "video_download_count", "video_comment_count"]
FEATURES = COUNTERS + ["video_duration_sec", "verified", "banned", "under_review"]
LONE = "video_view_count"          # the one column the control model is allowed to see

LABELS = {
    "video_view_count": "Visualizaciones", "video_like_count": "Me gusta",
    "video_share_count": "Compartidos", "video_download_count": "Descargas",
    "video_comment_count": "Comentarios", "video_duration_sec": "Duración",
    "verified": "Cuenta verificada", "banned": "Autor expulsado",
    "under_review": "Autor en revisión",
}


def load(results: Results) -> pd.DataFrame:
    banner("1. Los datos, y el objetivo que cambia respecto al Curso 4")
    df = pd.read_csv(dataset(SLUG))
    results.put("data.rows_raw", len(df), "filas en el CSV")
    results.put("data.rows_incomplete", int(df.isna().any(axis=1).sum()),
                "filas incompletas, las mismas 298 del Curso 2")

    df = df.dropna().copy()
    df["is_claim"] = df.claim_status.eq("claim").astype(int)
    df["verified"] = df.verified_status.eq("verified").astype(int)
    df["banned"] = df.author_ban_status.eq("banned").astype(int)
    df["under_review"] = df.author_ban_status.eq("under review").astype(int)

    results.put("data.rows_clean", len(df), "filas completas")
    results.put("data.claim_pct", round(100 * float(df.is_claim.mean()), 1),
                "porcentaje de reclamaciones")
    # The Course 4 target was verified_status, at 93.6 % against 6.4 %, so that project had
    # to downsample. This one is balanced by nature and needs nothing.
    results.put("data.needs_balancing", False,
                "¿hace falta equilibrar? En el Curso 4 sí, aquí no")

    views = df.groupby("claim_status").video_view_count
    results.put("signal.claim_mean_views", round(float(views.mean()["claim"]), 1))
    results.put("signal.opinion_mean_views", round(float(views.mean()["opinion"]), 1))
    results.put("signal.view_ratio",
                round(float(views.mean()["claim"] / views.mean()["opinion"]), 1),
                "cuántas veces más se ve una reclamación, el hallazgo del Curso 2")
    results.put("signal.opinion_max_views", int(views.max()["opinion"]),
                "la opinión más vista de todo el archivo")
    results.put("signal.claim_min_views", int(views.min()["claim"]),
                "la reclamación menos vista")
    return df


def split(df: pd.DataFrame, results: Results) -> tuple[pd.DataFrame, ...]:
    banner("2. Partición en tres, con la prueba apartada desde el principio")
    rest, test = train_test_split(df, test_size=0.20, random_state=SEED,
                                  stratify=df.is_claim)
    train, validation = train_test_split(rest, test_size=0.25, random_state=SEED,
                                         stratify=rest.is_claim)
    for name, part in [("train", train), ("validation", validation), ("test", test)]:
        results.put(f"split.{name}_rows", len(part))
    print(f"  entrenamiento {len(train)}   validación {len(validation)}   prueba {len(test)}")
    return train, validation, test


def lone_question(train, validation, results: Results) -> DecisionTreeClassifier:
    """The control: one cut, one column. Everything else is measured against this.

    Fitted before the real models on purpose. Deciding afterwards what counts as a good
    baseline is how a project talks itself into being impressed by its own result.
    """
    banner("3. El control: un árbol de UNA pregunta sobre UNA columna")
    stump = DecisionTreeClassifier(max_depth=1, random_state=SEED).fit(
        train[[LONE]], train.is_claim)
    cut = float(stump.tree_.threshold[0])
    results.put("lone.column", LONE)
    results.put("lone.threshold", round(cut, 1), "el corte que eligió, en visualizaciones")

    accuracy = accuracy_score(validation.is_claim, stump.predict(validation[[LONE]]))
    results.put("lone.validation_accuracy", round(float(accuracy), 4))
    print(f"  la regla entera: si el vídeo pasa de {cut:,.0f} visualizaciones, es "
          f"reclamación")
    print(f"  y con eso solo acierta el {100 * accuracy:.2f} % en validación")

    # How many videos in the whole file that one rule gets wrong, and who they are.
    wrong = ((train.claim_status.eq("opinion") & train[LONE].gt(cut)) |
             (train.claim_status.eq("claim") & train[LONE].le(cut)))
    results.put("lone.exceptions_train", int(wrong.sum()),
                "vídeos del entrenamiento que esa regla se salta")
    results.put("lone.exceptions_are_claims",
                int((wrong & train.claim_status.eq("claim")).sum()),
                "  de ellos, reclamaciones con pocas visualizaciones")
    return stump


def candidates(train, validation, results: Results) -> dict:
    banner("4. Los candidatos de verdad, con las nueve variables")
    X, y = train[FEATURES], train.is_claim
    Xv, yv = validation[FEATURES], validation.is_claim
    models = {
        "logistica": LogisticRegression(max_iter=3000),
        "arbol": DecisionTreeClassifier(random_state=SEED),
        "bosque": RandomForestClassifier(n_estimators=300, random_state=SEED, n_jobs=-1),
        "xgboost": XGBClassifier(n_estimators=300, max_depth=4, learning_rate=0.1,
                                 eval_metric="logloss", random_state=SEED, n_jobs=1),
    }
    for name, model in models.items():
        model.fit(X, y)
        auc = roc_auc_score(yv, model.predict_proba(Xv)[:, 1])
        accuracy = accuracy_score(yv, model.predict(Xv))
        results.put(f"candidates.{name}_auc", round(float(auc), 4))
        results.put(f"candidates.{name}_accuracy", round(float(accuracy), 4))
        print(f"  {name:11} AUC {auc:.4f}   exactitud {accuracy:.4f}")
    return models


def tune(train, validation, results: Results) -> dict:
    banner("5. Ajuste de perillas")
    X, y = train[FEATURES], train.is_claim
    Xv, yv = validation[FEATURES], validation.is_claim
    tuned = {}
    grids = {
        "bosque": (RandomForestClassifier(n_estimators=300, random_state=SEED, n_jobs=-1),
                   {"max_depth": [3, 5, 8, None], "min_samples_leaf": [1, 5, 20],
                    "max_features": ["sqrt", 0.5]}),
        "xgboost": (XGBClassifier(eval_metric="logloss", random_state=SEED, n_jobs=1),
                    {"max_depth": [2, 3, 5], "learning_rate": [0.05, 0.1],
                     "n_estimators": [200, 400]}),
    }
    for name, (estimator, grid) in grids.items():
        combinations = int(np.prod([len(v) for v in grid.values()]))
        started = time.perf_counter()
        search = GridSearchCV(estimator, grid, cv=4, scoring="roc_auc", n_jobs=-1).fit(X, y)
        elapsed = time.perf_counter() - started
        auc = roc_auc_score(yv, search.best_estimator_.predict_proba(Xv)[:, 1])
        results.put(f"tuning.{name}.combinations", combinations)
        results.put(f"tuning.{name}.seconds", round(elapsed, 1))
        results.put(f"tuning.{name}.best_params",
                    {k: str(v) for k, v in search.best_params_.items()})
        results.put(f"tuning.{name}.cv_auc", round(float(search.best_score_), 4))
        results.put(f"tuning.{name}.validation_auc", round(float(auc), 4))
        print(f"  {name:8} {combinations} combinaciones en {elapsed:4.0f} s   AUC {auc:.4f}")
        tuned[name] = search.best_estimator_
    return tuned


def measure(model, features, truth, results: Results, prefix: str) -> dict:
    probability = model.predict_proba(features)[:, 1]
    decision = (probability >= 0.5).astype(int)
    scores = {
        "accuracy": accuracy_score(truth, decision),
        "precision": precision_score(truth, decision, zero_division=0),
        "recall": recall_score(truth, decision),
        "f1": f1_score(truth, decision),
        "auc": roc_auc_score(truth, probability),
    }
    for name, value in scores.items():
        results.put(f"{prefix}.{name}", round(float(value), 4))
    return scores


# ------------------------------------------------------------------------- figures

def figure_the_cut(df: pd.DataFrame, results: Results) -> None:
    """Where the threshold sits, and why anything finds it."""
    style()
    cut = results.data["lone"]["threshold"]
    fig, ax = plt.subplots(figsize=WIDE)
    edges = np.logspace(np.log10(20), np.log10(1_100_000), 60)
    for key, name, colour in [("opinion", "De opinión", AZURITE),
                              ("claim", "Con reclamación", GOLD)]:
        ax.hist(df.loc[df.claim_status.eq(key), "video_view_count"], bins=edges,
                color=colour, alpha=0.9, edgecolor=SURFACE, linewidth=0.5, label=name,
                zorder=2)
    ax.axvline(cut, color=GRAPHITE, linewidth=1.8, zorder=5)
    ax.annotate(f"el corte del modelo\n{thousands(round(cut))}",
                xy=(cut, 0.95), xycoords=("data", "axes fraction"), xytext=(10, 0),
                textcoords="offset points", va="top", fontsize=ANNOTATION, weight="bold",
                color=GRAPHITE)

    ax.set_xscale("log")
    ax.set_xlabel("Visualizaciones por vídeo")
    ax.set_ylabel("Número de vídeos")
    ax.xaxis.set_major_formatter(plt.FuncFormatter(
        lambda v, _: thousands(v) if v < 1000 else
        (f"{v / 1000:g} mil" if v < 1_000_000 else f"{v / 1_000_000:g} M")))
    ax.legend(loc="upper center", frameon=False, fontsize=ANNOTATION, ncols=2)
    ax.set_title("Las dos clases están separadas por una línea, y el modelo la encuentra",
                 loc="left", fontsize=TITLE, weight="bold", pad=16)
    ax.grid(axis="x", visible=False)

    top = results.data["signal"]["opinion_max_views"]
    fig.text(0.005, -0.05,
             f"Qué mirar: la opinión más vista de todo el archivo tiene "
             f"{thousands(top)} visualizaciones, y el corte cae en "
             f"{thousands(round(cut))}. Prácticamente no hay solape.",
             fontsize=CAPTION, color=GRAPHITE, style="italic")
    fig.text(0.005, -0.12,
             "Un hueco así no aparece en datos de una plataforma real. Aparece cuando "
             "alguien genera dos poblaciones con rangos distintos, y estos datos son "
             "sintéticos.",
             fontsize=CAPTION, color=MUTED)
    FIGURES.mkdir(parents=True, exist_ok=True)
    save_figure(fig, FIGURES, "01_el_corte.png")
    plt.close(fig)


def figure_one_question(results: Results) -> None:
    """The control against the contenders, which is the argument of the project."""
    style()
    rows = [
        ("Una pregunta,\nuna columna", results.data["test"]["lone"]["accuracy"], GOLD),
        ("Regresión logística\n9 variables", results.data["test"]["logistica"]["accuracy"],
         MUTED),
        ("Refuerzo ajustado\n9 variables", results.data["test"]["xgboost"]["accuracy"],
         AZURITE),
        ("Bosque ajustado\n300 árboles, 9 variables",
         results.data["test"]["bosque"]["accuracy"], AZURITE),
    ]
    fig, ax = plt.subplots(figsize=WIDE)
    positions = np.arange(len(rows))[::-1]
    bars = ax.barh(positions, [value for _, value, _ in rows],
                   color=[colour for *_, colour in rows], height=0.58,
                   edgecolor=SURFACE, linewidth=1.2, zorder=2)
    for bar, (_, value, _) in zip(bars, rows):
        ax.annotate(decimal(value), xy=(value, bar.get_y() + bar.get_height() / 2),
                    xytext=(8, 0), textcoords="offset points", va="center",
                    fontsize=ANNOTATION, weight="bold", color=GRAPHITE)
    ax.axvline(results.data["test"]["lone"]["accuracy"], color=GOLD, linewidth=1.4,
               linestyle=(0, (4, 3)), zorder=4)

    ax.set_yticks(positions, [name for name, *_ in rows])
    ax.set_xlim(0.985, 0.999)
    ax.set_xlabel("Exactitud sobre el conjunto de prueba")
    ax.set_title("Trescientos árboles no le ganan a una sola pregunta", loc="left",
                 fontsize=TITLE, weight="bold", pad=16)
    ax.grid(axis="y", visible=False)

    lone = results.data["test"]["lone"]["accuracy"]
    forest = results.data["test"]["bosque"]["accuracy"]
    fig.text(0.005, -0.06,
             f"Qué mirar: la línea de puntos es lo que consigue preguntar una sola vez por "
             f"una sola columna, {decimal(lone)}. El bosque ajustado, con nueve variables y "
             f"trescientos árboles, saca {decimal(forest)}.\nEl eje empieza en 0,985 para "
             f"que se vea algo, y aun así las barras son casi iguales.",
             fontsize=CAPTION, color=GRAPHITE, style="italic")
    fig.text(0.005, -0.15,
             "Cuando el modelo complicado no le gana al control más tonto que se te ocurra, "
             "el mérito no es del modelo: la señal ya estaba en el dato.",
             fontsize=CAPTION, color=MUTED)
    save_figure(fig, FIGURES, "02_una_pregunta.png")
    plt.close(fig)


def figure_importance(forest, results: Results) -> None:
    style()
    pairs = sorted(zip(FEATURES, forest.feature_importances_), key=lambda t: t[1])
    for name, value in pairs:
        results.put(f"importance.{name}", round(float(value), 4))

    fig, ax = plt.subplots(figsize=TALL)
    counters = set(COUNTERS)
    bars = ax.barh([LABELS[name] for name, _ in pairs], [value for _, value in pairs],
                   color=[GOLD if name in counters else AZURITE for name, _ in pairs],
                   height=0.62, edgecolor=SURFACE, linewidth=1.1, zorder=2)
    for bar, (_, value) in zip(bars, pairs):
        ax.annotate(decimal(value), xy=(value, bar.get_y() + bar.get_height() / 2),
                    xytext=(6, 0), textcoords="offset points", va="center",
                    fontsize=CAPTION, weight="bold", color=GRAPHITE)
    ax.set_xlim(0, max(value for _, value in pairs) * 1.2)
    ax.set_xlabel("Importancia dentro del bosque")
    ax.set_title("Los cinco contadores son el modelo entero", loc="left", fontsize=TITLE,
                 weight="bold", pad=16)
    ax.grid(axis="y", visible=False)

    share = sum(value for name, value in pairs if name in counters)
    fig.text(0.005, -0.04,
             f"Qué mirar: en dorado los cinco contadores de interacción, que suman "
             f"{decimal(share)} de la importancia. En azul todo lo demás, incluido si la "
             f"cuenta está verificada, que aporta exactamente cero.",
             fontsize=CAPTION, color=GRAPHITE, style="italic")
    fig.text(0.005, -0.12,
             "Y los cinco contadores están correlacionados entre sí por encima de 0,55, "
             "según el mapa del Curso 4. O sea que esto no son cinco señales: es una, "
             "repartida.",
             fontsize=CAPTION, color=MUTED)
    save_figure(fig, FIGURES, "03_importancia.png")
    plt.close(fig)


def figure_exceptions(train: pd.DataFrame, results: Results) -> None:
    """The videos the one rule gets wrong, which are the only interesting ones left."""
    style()
    cut = results.data["lone"]["threshold"]
    wrong = ((train.claim_status.eq("opinion") & train[LONE].gt(cut)) |
             (train.claim_status.eq("claim") & train[LONE].le(cut)))
    exceptions = train[wrong]

    fig, ax = plt.subplots(figsize=WIDE)
    ax.hist(exceptions[LONE], bins=25, color=GOLD, alpha=0.95, edgecolor=SURFACE,
            linewidth=1.0, zorder=2)
    ax.axvline(cut, color=GRAPHITE, linewidth=1.6, zorder=4)
    ax.annotate(f"el corte, en {thousands(round(cut))}", xy=(cut, 0.9),
                xycoords=("data", "axes fraction"), xytext=(-10, 0),
                textcoords="offset points", ha="right", va="top", fontsize=ANNOTATION,
                weight="bold", color=GRAPHITE)
    ax.set_xlabel("Visualizaciones del vídeo")
    ax.set_ylabel("Número de vídeos")
    ax.set_title("Los únicos vídeos difíciles del archivo, y son 96 de 19.084", loc="left",
                 fontsize=TITLE, weight="bold", pad=16)
    ax.grid(axis="x", visible=False)

    count = results.data["lone"]["exceptions_train"]
    claims = results.data["lone"]["exceptions_are_claims"]
    fig.text(0.005, -0.05,
             f"Qué mirar: son {thousands(count)} vídeos del entrenamiento, y "
             f"{thousands(claims)} de ellos son reclamaciones que casi nadie vio. Todos "
             f"caen a la izquierda del corte.",
             fontsize=CAPTION, color=GRAPHITE, style="italic")
    fig.text(0.005, -0.12,
             "Estos son los que un modelo mejor tendría que resolver, y ninguno de los "
             "cuatro los resuelve: la diferencia entre 0,9958 y 0,9986 de AUC se juega "
             "entera aquí dentro.",
             fontsize=CAPTION, color=MUTED)
    save_figure(fig, FIGURES, "04_excepciones.png")
    plt.close(fig)


def main() -> None:
    results = Results(SLUG, "TikTok: reclamación u opinión, y quién hizo el trabajo", COURSE)
    df = load(results)
    train, validation, test = split(df, results)

    stump = lone_question(train, validation, results)
    plain = candidates(train, validation, results)
    tuned = tune(train, validation, results)

    banner("6. El campeón, elegido en validación")
    Xv, yv = validation[FEATURES], validation.is_claim
    finalists = {"logistica": plain["logistica"], "bosque": tuned["bosque"],
                 "xgboost": tuned["xgboost"]}
    on_validation = {name: roc_auc_score(yv, model.predict_proba(Xv)[:, 1])
                     for name, model in finalists.items()}
    champion = max(on_validation, key=on_validation.get)
    for name, auc in on_validation.items():
        results.put(f"finalists.{name}_validation_auc", round(float(auc), 4))
    results.put("champion", champion)
    print(f"  campeón: {champion}")

    banner("7. La prueba, una sola vez, incluido el control")
    measure(stump, test[[LONE]], test.is_claim, results, "test.lone")
    for name, model in finalists.items():
        scores = measure(model, test[FEATURES], test.is_claim, results, f"test.{name}")
        print(f"  {name:11} AUC {scores['auc']:.4f}   exactitud {scores['accuracy']:.4f}")
    lone_accuracy = results.data["test"]["lone"]["accuracy"]
    print(f"  {'una pregunta':11} AUC {results.data['test']['lone']['auc']:.4f}   "
          f"exactitud {lone_accuracy:.4f}")

    banner("8. El veredicto")
    best = max(results.data["test"][name]["accuracy"] for name in finalists)
    results.put("verdict.lone_accuracy", lone_accuracy)
    results.put("verdict.best_model_accuracy", round(float(best), 4))
    results.put("verdict.gain_over_one_question", round(float(best - lone_accuracy), 4),
                "lo que aportan nueve variables y trescientos árboles sobre una pregunta")
    print(f"  una pregunta:      {lone_accuracy:.4f}")
    print(f"  el mejor modelo:   {best:.4f}")
    print(f"  lo que aportó todo lo demás: {best - lone_accuracy:+.4f}")

    banner("9. Figuras")
    figure_the_cut(df, results)
    figure_one_question(results)
    figure_importance(tuned["bosque"], results)
    figure_exceptions(train, results)
    for figure in sorted(FIGURES.glob("*.png")):
        print(f"  {figure.name}")

    results.write()


if __name__ == "__main__":
    main()
